---
- name: Installation de l'environnement de développement Web
  hosts: localhost
  become: yes
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
      become: yes

    - name: Installation de Fish
      apt:
        name: fish
        state: present
      become: yes

    - name: Définir Fish comme shell par défaut
      command: chsh -s /usr/bin/fish
      become: yes

    - name: Configuration de Fish
      template:
        src: fish_config.fish
        dest: ~/.config/fish/config.fish
        mode: 0644
      become: yes

    - name: Installation de Tmux
      apt:
        name: tmux
        state: present
      become: yes

    - name: Configuration de Tmux
      template:
        src: tmux_config.conf
        dest: ~/.tmux.conf
        mode: 0644
      become: yes

  handlers:
    - name: Redémarrer le shell utilisateur
      command: exec su -l "{{ ansible_user }}" -c fish
