# Étape 1 : Créer une build du projet React
FROM node:14-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Étape 2 : Utiliser Nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers de build du projet React dans le répertoire de Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Copier la configuration personnalisée de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80 pour le trafic entrant
EXPOSE 80

# Démarrer Nginx lors du lancement du conteneur
CMD ["nginx", "-g", "daemon off;"]
