# Builder l'application React
# FROM node:14-alpine as builder

# WORKDIR /app/web

# COPY package*.json ./
# RUN npm install

# COPY . .

# RUN npm run build

# Exécuter le serveur Web
FROM nginx:latest

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY --from=builder /app/web/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
